"""API endpoints - Generated by AI coding assistant."""
from flask import Flask, request, jsonify
from auth.login import login, authenticate
from payment.process import process_payment
from admin.dashboard import admin_dashboard

app = Flask(__name__)

@app.route("/api/login", methods=["POST"])
def api_login():
    return login()

@app.route("/api/payment", methods=["POST"])
def api_payment():
    # AI-generated: No auth check added
    return process_payment()

@app.route("/api/admin", methods=["GET"])
def api_admin():
    # AI-generated: Missing authentication decorator
    return admin_dashboard(request)

@app.route("/api/users", methods=["GET"])
def api_users():
    """List users - AI generated, no PII filtering."""
    from admin.dashboard import get_all_users
    return jsonify(get_all_users())

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
